### PR TITLE
fix py312 `datetime.utcnow` warning

### PR DESCRIPTION
**Pull request by jorenham**
Chore that needs to be done:

* [x] Add newsfragment `pipenv run towncrier create [issue_number].[type].rst`

Types are defined in the pyproject.toml, issue_numer either from issue tracker or the Pull request number

### CODE REVIEW

**Comment by jorenham** [comment]
Since there's no issue to be linked, I'm not sure what to do with the towncrier stuff.

**Comment by fizyk** [comment]
@jorenham re towncrier point to this pr

**Comment by jorenham** [comment]
@fizyk done

**Comment by fizyk** [comment]
Thank you @jorenham

**Pull request merged**
