### PR TITLE
add dataistemplate

### PR DESCRIPTION
**Pull request by uosjead**
Chore that needs to be done:

* [ ] Add newsfragment `pipenv run towncrier create [issue_number].[type].rst`

Types are defined in the pyproject.toml, issue_numer either from issue tracker or the Pull request number

### CODE REVIEW

**Comment by fizyk** [comment]
Could you rebase with master and write some explanation? a newsfragment with details of the change?

**Comment by uosjead** [comment]
> Could you rebase with master and write some explanation? a newsfragment with details of the change?

Yeah apologies! I meant to create this pull request on my forked branch first 🤦

**Comment by fizyk** [comment]
@uosjead I've incorporated your idea and actually implemented this on master

**Comment by uosjead** [comment]
> @uosjead I've incorporated your idea and actually implemented this on master

Ah great! Thanks for implementing

**Pull request closed without merging**
